# Config file of ${project.name}.
# This file was originally created by version ${project.version}.

# All types of containers that can be protected.
# All material names can be found here:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
protectableContainers:
  - anvil
  - chipped_anvil
  - damaged_anvil
  - barrel
  - beacon
  - brewing_stand
  - black_shulker_box
  - blue_shulker_box
  - brown_shulker_box
  - cyan_shulker_box
  - gray_shulker_box
  - green_shulker_box
  - light_blue_shulker_box
  - light_gray_shulker_box
  - lime_shulker_box
  - magenta_shulker_box
  - orange_shulker_box
  - pink_shulker_box
  - purple_shulker_box
  - red_shulker_box
  - shulker_box
  - white_shulker_box
  - yellow_shulker_box
  - chest
  - crafting_table
  - blast_furnace
  - dispenser
  - dropper
  - enchanting_table
  - furnace
  - hopper
  - jukebox
  - smoker
  - trapped_chest

# When set to true, one sign protects all connected nearby blocks of the same
# type. When false, each container requires a separate sign.
# Please note that a double chest is one container, so one sign is enough to
# protect the whole chest, regardless of this setting.
connectContainers: false

# All types of doors that can be protected. These blocks must follow the data
# value format as described here:
# http://minecraft.gamepedia.com/Data_values#Door
protectableDoors:
  - acacia_door
  - birch_door
  - dark_oak_door
  - iron_door
  - jungle_door
  - oak_door
  - spruce_door

# All protections (except doors) that consist not only of the block listed here,
# but also of a supporting block. This is normally the block directly below.
# For example, for fence gates both the gate and the block below are protected,
# and signs can be attached to both.
# Note that for some blocks (like trapdoors, but also levers if you would add
# them here) the supporting block is not the block below, but the block it is
# attached on.
protectableAttachables:
  - acacia_fence_gate
  - acacia_trapdoor
  - birch_fence_gate
  - birch_trapdoor
  - dark_oak_fence_gate
  - dark_oak_trapdoor
  - iron_trapdoor
  - jungle_fence_gate
  - jungle_trapdoor
  - oak_fence_gate
  - oak_trapdoor
  - spruce_fence_gate
  - spruce_trapdoor

# Aside from players breaking protections, this plugin also prevents other things
# (creepers and TNT for example) from breaking protections. You can add things here
# if you want those things to destroy protections.
# For example,  allowDestroyBy: [CREEPER, TNT]  allows creepers and TNT to destroy
# protections.
#
# These are the values you can use, along with how they can destroy protections.
# CREEPER - creepers can destroy protections by exploding
# ENDERMAN - endermans can destroy protections by picking up blocks
# FIRE - fire can burn protections
# GHAST - ghasts can shoot exploding fireballs
# PISTON - pistons can remove the protection signs
# SAPLING - saplings can grow trees, destroying protection signs
# TNT - TNT can destroy protections by exploding
# ZOMBIE - zombies can destroy protected doors
# UNKNOWN - special value for all other unrecognized attacks
allowDestroyBy: []